name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us identify and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or paste links

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Scanner Service (Go)
        - NLP Service (Python)
        - API Service (Go)
        - Frontend (React)
        - Database/Storage
        - Docker/Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you using?
      placeholder: v1.0.0 or commit hash
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      value: |
        - OS: [e.g. Ubuntu 20.04, macOS 12.0, Windows 11]
        - Docker Version: [e.g. 20.10.17]
        - Docker Compose Version: [e.g. 2.6.1]
        - Browser: [e.g. Chrome 108, Firefox 107] (if frontend issue)
        - Available RAM: [e.g. 8GB]
        - Available Storage: [e.g. 100GB free]
    validations:
      required: true

  - type: textarea
    id: media-info
    attributes:
      label: Media Information (if applicable)
      description: Information about the media files being processed
      placeholder: |
        - File types: [e.g. .mp4, .srt]
        - File sizes: [e.g. 1-5GB videos, 1-50KB subtitles]
        - Number of files: [e.g. ~500 files]
        - Library structure: [e.g. Movies/TV Shows folders]

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please include relevant logs from `docker-compose logs` or individual services
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove any sensitive information)
      placeholder: |
        # docker-compose.yml environment variables
        # scanner configuration
        # Any custom settings
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information above
          required: true
        - label: I have removed any sensitive information from logs/config
          required: true